### ISSUE TITLE
洗衣机查询 iOS Shortcuts

### ISSUE THREAD

**Issue by bohaothu** [ZenithalHourlyRate/thuservices#3]
https://www.icloud.com/shortcuts/ffc9d9fff7e140ec9e5a92e5f7d16ae0

**Comment by ZenithalHourlyRate** [comment]
经过 @FactorialN 的测试，此链接可用，可以收录
您是想自己发一个 pr ，加上链接和使用说明呢，还是我这边写然后 co-author 您

**Comment by bohaothu** [comment]
我发个 PR 吧

**Comment by ZenithalHourlyRate** [comment]
已经接受 PR
