### ISSUE TITLE
rsshub更新

### ISSUE THREAD

**Issue by fredericky123** [ZenithalHourlyRate/thuservices#30]
大佬好！
能否继续维护更新这两个rss订阅源，目前好像不能用了吧？
 https://rsshub.app/thu/zhongyao
https://rsshub.app/thu/career 
很需要招聘信息，感谢感谢！

**Comment by ZenithalHourlyRate** [comment]
@fredericky123 这个问题似乎在 github.com/diygod/rsshub 那边提更好？

**Comment by fredericky123** [comment]
我看你之前提交了路由规则，想着完善下可能比较快，我之前在rsshub那边提了，可是无人完善（也许是受众不是很duo的缘故吧）

**Comment by ZenithalHourlyRate** [comment]
@fredericky123 我印象中我没交过路由规则啊
