### ISSUE TITLE
更新services.md里面的BANNED PORTS

### ISSUE THREAD

**Issue by 84634E1A607A** [ZenithalHourlyRate/thuservices#39]
10/15/2022晚测试的结果, 通过校外nmap扫我本机的1-20000端口, 分析收到的包得来. 本机位于183.172.0.0/16段:

多了1080 (不知道有啥用), 4781 (这个更不知道了), 7890 (懂得都懂), 9100 (这个端口好像也挺常用)

1-1024
1080-1080
3389-3389
4781-4781
7890-7890
8000-8100
9100-9100

**Comment by dramforever** [comment]
@84634E1A607A 哈哈？

**Comment by prnake** [comment]
- 1080：V2Ray 默认端口
- 4781：一些机场定制客户端的默认端口
- 7890：Clash 默认端口
- 9100：网络打印机
