### ISSUE TITLE
新的选课脚本

### ISSUE THREAD

**Issue by 84634E1A607A** [ZenithalHourlyRate/thuservices#42]
https://greasyfork.org/en/scripts/456440-colorful-course

刚刚写的, 用于研究什么志愿能报. 暂不支持体育课 (因为我用不到). 欢迎使用~

**Comment by ZenithalHourlyRate** [comment]
> 欢迎使用~

您可以发一个 PR 增加该工具

**Comment by 84634E1A607A** [comment]
aux拒我于门外

**Comment by ZenithalHourlyRate** [comment]
@84634E1A607A 垃圾 Windows！！！！

**Comment by ZenithalHourlyRate** [comment]
那我加一下? 用什么做描述比较好

**Comment by 84634E1A607A** [comment]
这就换linux

**Comment by 84634E1A607A** [comment]
其实我也不知道怎么描述比较好。。。

**Comment by 84634E1A607A** [comment]
## 选课剩余课容标记

不知道该用什么志愿抢课？
这个脚本帮你忙！

这个脚本为报名人数上色，最后一个绿色就是最佳抢课志愿了！

脚本还在开发中，体育课支持等即将上线！

访问[这里](https://greasyfork.org/en/scripts/456440-colorful-course)获取脚本

···


## 选课剩余课容标记

不知道该用什么志愿抢课？
这个脚本帮你忙！

这个脚本为报名人数上色，最后一个绿色就是最佳抢课志愿了！

脚本还在开发中，体育课支持等即将上线！

访问[这里](https://greasyfork.org/en/scripts/456440-colorful-course)获取脚本
···

如何 （

**Comment by ZenithalHourlyRate** [comment]
可以可以，那我直接 commit 了?

**Comment by 84634E1A607A** [comment]
```
## 选课剩余课容标记

不知道该用什么志愿抢课？
这个脚本帮你忙！

这个脚本为报名人数上色，最后一个绿色就是最佳抢课志愿了！

脚本还在开发中，队列支持等即将上线！

访问[这里](https://greasyfork.org/en/scripts/456440-colorful-course)获取脚本
```

这个？ 刚刚体育课加上去了

**Comment by ZenithalHourlyRate** [comment]
https://github.com/ZenithalHourlyRate/thuservices/commit/2d8bd9e012b96bcfbe8766012b93ab0e8b5bee93

**Comment by 84634E1A607A** [comment]
好耶！
