### ISSUE TITLE
关于云盘 cli 客户端使用

### ISSUE THREAD

**Issue by InvincibleWyq** [ZenithalHourlyRate/thuservices#52]
2021年，下述PR合入了关于seafile云盘 cli 客户端的使用指南
https://github.com/ZenithalHourlyRate/thuservices/pull/26/files

我对照操作后，发现已有部分变化：
首先网页端cookie中没有seahub_auth字段，仅有sfcsrftoken，它是一串没有模式的字符串，已经不符合 [学号@tsinghua.edu.cn@Token] 模式。
我假定sfcsrftoken字段就是我们需要的token。之后再运行如下命令：
`seaf-cli sync -l <library-id> -s https://cloud.tsinghua.edu.cn/ -d <place-directory> -T <token>`
<img width="751" alt="image" src="https://github.com/ZenithalHourlyRate/thuservices/assets/37479394/0a0d0806-849d-4b90-b796-8187fd72e748">

此时会询问我的Enter Username，不论键入何种Username（例如学号@ tsinghua.edu.cn、学号，等等），服务器均回复：

> urllib.error.HTTPError: HTTP Error 401: Unauthorized

我的seaf-cli客户端虽为7.0版本，但已按照说明操作，按说已可以使用token同步。请问该方法是否已经变化？谢谢！@prnake

**Comment by prnake** [comment]
假如找不到seahub_auth字段，可以重新登陆网页版 ，只有在登陆跳转后的前几个请求中存在这个cookie

**Comment by InvincibleWyq** [comment]
@prnake 谢谢！退出重登后找到seahub_auth字段，目前已经可以成功sync，感谢！！！
