### ISSUE TITLE
研究生 GPA 计算问题

### ISSUE THREAD

**Issue by SuXY15** [ZenithalHourlyRate/thuservices#7]
代码中略去了最后一行，不清楚本科生的如何，但是研究生的最后一行是有效课程
``` javascript
...
for(var i=1;i<table.rows.length-1;++i){ // skip the first and last row
        var r = table.rows[i]
...
```
除去最后一行会导致计算错误

**Comment by ZenithalHourlyRate** [comment]
本科生最后一行表示的是学分量，需要去掉。
```
必修课总学分：xx | 限选课总学分：xx | 任选课总学分：xx 
```
对于此行，其属性 `r.cells.length` 为 1（定义参见代码）。

想问一下研究生此行的 `r.cells.length` 为多少，如何选取该行数据？该行数据与之前行的数据是否是一致的？

如果该行与之前相同，那么可以直接在 for 循环中加上这行，因为根据 `r.cells.length` 可以判断该行是否有效。

欢迎PR

**Comment by ZenithalHourlyRate** [comment]
Resolved by #8
